--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.6.4"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: 
            - "v1-dependencies-{{ checksum \"requirements.txt\" }}"
            - v1-dependencies-
      - 
        run: 
          command: |
              python -m venv venv
              . venv/bin/activate
              make install
          name: "install dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"requirements.txt\" }}"
          paths: 
            - .venv
      - 
        run: 
          command: |
              . venv/bin/activate
              make lint
          name: "run lint"
    working_directory: ~/containerisedflaskapp
version: 2
